### ISSUE TITLE
gz-math: Rotation example

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1380] opened 2024-08-29 05:58 UTC
## Configuration

* os: Ubuntu Noble

## Links

* [Live](https://gazebosim.org/api/math/8/rotation.html)
* [Source](https://github.com/gazebosim/gz-math/tree/gz-math8/tutorials/rotation.md)

**Comment by alesof** [comment] 2024-08-31 16:22
This is a duplicate of #1382. I think this was created because there are two different urls ([url1](https://gazebosim.org/api/math/8/rotation_example.html), [url2](https://gazebosim.org/api/math/8/rotation.html)) containing the same tutorial.

**Comment by ahcorde** [comment] 2024-09-02 08:41
Related https://github.com/gazebosim/gz-math/pull/627

**Closed as completed** 2024-09-02 08:41 UTC
Labels: gz-math, ionic, version: 0.0.1, os: Ubuntu Noble
