### ISSUE TITLE
gz-sim: multicopter_velocity_control.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#333] opened 2023-08-31 15:56 UTC
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/multicopter_velocity_control.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by jchaudhary21** [comment] 2023-09-07 09:48
**_Works, as per  instructions._**
![Screenshot from 2023-09-07 14-56-21](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/2dd16338-8b0d-4fd5-865f-b798c2ef3fd7)

**_But warning  message also appears on terminal_** 
![Screenshot from 2023-09-07 15-09-43](https://github.com/gazebosim/gazebo_test_cases/assets/96059006/ffca7059-d696-4a6c-9b32-bc24d0ebacca)

```
Warning [Utils.cc:130] [/sdf/model[@name="X4"]/link[@name="base_link"]/sensor[@name="air_pressure"]/air_pressure/noise:/home/jc/.gz/fuel/fuel.gazebosim.org/openrobotics/models/x4 uav config 1/14/model.sdf:L226]: XML Element[noise], child of element[air_pressure], not defined in SDF. Copying[noise] as children of [air_pressure].```

**Comment by Voldivh** [comment] 2023-09-07 14:07
Thanks @jchaudhary21, I'll take note of the warning message. Closing this issue as completed for now.

**Comment by Voldivh** [comment] 2023-09-08 18:02
> @Voldivh, there is a minor issue that I'm facing with this simulation. The instructions that are given don't get executed in one go. I have to run it multiple times, and after that, it gets executed.

I was unable to reproduce that behavior, I just had to send the command once and it worked just fine (for both robots). Could you perhaps take a at the terminal where you ran the `gz sim` command and see if you get some error or something like that?

**Comment by jchaudhary21** [comment] 2023-09-08 18:26
Apart from those warnings which I mention above , there are no additional errors . 

Then I think it is more of my pc's problem . Ok, I will try this simulation on some other system and will let you know if problem persists .

**Comment by Voldivh** [comment] 2023-09-08 19:22
@jchaudhary21 Regarding the warning that appears when launching the world, the issue is a definition on the model we import for the X4 robot. We will do the modifications for a next iteration so let me know how it goes in your other system so I can close this issue. Once again thanks for testing it out!

**Comment by jchaudhary21** [comment] 2023-09-09 15:08
Just tested this on another system, and it's working fine . You may close this issue .

**Comment by Voldivh** [comment] 2023-09-09 15:24
Thanks @jchaudhary21

**Closed by Voldivh** 2023-09-09 15:25 UTC
Labels: harmonic, Ubuntu Jammy, Binary, generation-1, gz-sim, sdf worlds
