### ISSUE TITLE
gz-sim: shapes_bitmask.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1676] opened 2024-08-29 07:29 UTC
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/shapes_bitmask.sdf)

**Comment by bperseghetti** [comment] 2024-08-29 16:21
I'm available to test.

**Comment by david-dorf** [comment] 2024-08-31 18:41
[Screencast from 2024-08-31 14-36-30.webm](https://github.com/user-attachments/assets/2a61280e-f8db-4b76-9398-d584d2b454f8)
Generally worked (Red and Green did not collide but both did with Yellow), however moving the box underneath Green didn't result in Green falling due to gravity. This probably isn't the plugin itself, but a problem with the sim physics itself. No meaningful errors or warnings occurred.

**Comment by azeey** [comment] 2024-09-16 19:25
@david-dorf I was unable to reproduce what I saw in the video. If you're able to reproduce it, could you please open an issue on gz-sim? I'll go ahead and close this issue since the transform tool problem is a separate issue.

**Closed by azeey** 2024-09-16 19:25 UTC
Labels: gz-sim, sdf worlds, ionic, version: 0.0.1, os: Any

**Comment by iche033** [comment] 2024-09-16 21:07
I also couldn't reproduce. Looks like somehow sim object poses ended up in a bad state.

**Comment by david-dorf** [comment] 2024-09-16 21:31
I’ll take another look when I get home, I agree it’s probably the transform
tool.
