### ISSUE TITLE
gz-sim: graded_buoyancy.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#261] opened 2023-08-31 15:45 UTC
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/graded_buoyancy.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by matosinho** [comment] 2023-09-10 15:36
Hello!

Very nice this graded_buoancy! How is it calculated? Do you check the percentage of the body which is on one side and on the other and compute both? Also, where are the forces applied?

The plugin itself seems to be working well, here is a gif:
![graded](https://github.com/gazebosim/gazebo_test_cases/assets/40249250/07722db2-0f7d-4de6-bd06-c8a5c7f524b4)

One thing though. The ```lighter_than_air``` ball comes back to the "water" surface after sometime and shoots up again. It is very fast, so you need to be focus to catch this. I'm not sure if it was supposed to be like this, that is why I'm commenting. Other than that, all good.

If any additional test is needed, let me know!

**Comment by Voldivh** [comment] 2023-09-12 17:19
Hey @matosinho glad it worked the demo for you. I tried it out and didn't notice any problem with the `lighter_than_air` ball, I was following the object along the simulation and it followed the expected behavior. On another note, take a look at the [buoyancy system](https://github.com/gazebosim/gz-sim/blob/gz-sim8/src/systems/buoyancy/Buoyancy.hh) and the [buoyancy engine](https://github.com/gazebosim/gz-sim/blob/gz-sim8/src/systems/buoyancy_engine/BuoyancyEngine.hh) if you would like to have more information regarding the implementation.

I'll be closing this issue as completed, since the world was loaded without any problems.

**Closed by Voldivh** 2023-09-12 17:19 UTC
Labels: harmonic, Ubuntu Jammy, Binary, generation-1, gz-sim, sdf worlds

**Comment by matosinho** [comment] 2023-09-21 20:19
Thank you
